### ISSUE TITLE
What are 'numeric flags'?

### ISSUE THREAD

**Issue by yleflour** [openstf/adbkit#40]
In the client.startActivity' method, it is written that the flags are to be passed as a numeric value.
Could this be explicited through an example?

In my case I to launch the following `adb shell am start -n com.package.name/.ActivityName` but don't know how to fill the config.

**Comment by sorccu** [comment]
It's essentially the same as [Intent.setFlags()](http://developer.android.com/reference/android/content/Intent.html#setFlags(int)), but without predefined constants. Decide which flags you need (which can already be quite difficult), and then binary-or them together as usual. You can get the numeric value of each flag by clicking on the flags in the linked documentation, which will then show their constant values. For example, if you want FLAG_ACTIVITY_CLEAR_TASK and FLAG_ACTIVITY_EXCLUDE_FROM_RECENTS, then your flags should be `flags: 0x00008000 | 0x00800000`.

Explaining which flags are necessary for what is beyond the scope of adbkit. However, you can use logcat and filter for activity manager events. When you launch an activity manually, you'll usually also see the flags they were launched with, which is great if you want to mimic real user actions. Anyway that's up to you.

I'm going to close this ticket for now since I don't have time to add an example, but if you get your thing working, please considering submitting a PR for the README. I'd be happy to accept it, as long as it follows the existing style. Plain JavaScript is fine.

**Comment by MathiasGilson** [comment]
that worked for me

```js
     client
     .startActivity(device.id, {
           wait: true,
           component: "package.name/.MyActivity"
     })
     .catch(console.error)
```
