### ISSUE TITLE
Get device temperature

### ISSUE THREAD

**Issue by jpklzm** [openstf/adbkit#45]
Is there anyway that I can get the device temperature like [TYPE_AMBIENT_TEMPERATURE](https://developer.android.com/reference/android/hardware/Sensor.html#TYPE_AMBIENT_TEMPERATURE)

**Comment by djimondev** [comment]
Did you try by using something like `adb shell dumpsys` ?

**Comment by sorccu** [comment]
Guys, I’ll close this because I don’t want the responsibility of making sure that the feature works on every SDK level. To be fair, we’ve already made the mistake of including unnecessarily complicated things in adbkit before, but for now let’s try to limit ourselves to the essentials.

If you need more functionality, you can create your own module that uses adbkit to do what it needs to do. For example, in this particular case, you could run the shell command suggested by @djimondev and simply parse the output (while making sure your parsing code works on every version).
